In [1]:
import pandas as pd
import numpy as np

In [2]:
# Import the data

orig_df = pd.read_csv('../data/ccRCC_TMT_intact glycopeptide_abundance_MD-MAD_50percentQuant_imputed.tsv', sep="\t")
df = orig_df.copy(deep=True)
df

,Index,CPT0079430001,CPT0023360001,CPT0023350003,CPT0079410003,CPT0087040003,CPT0077310003,CPT0077320001,CPT0087050003,NCI7.1,...,CPT0012080003,CPT0021240003,CPT0009020003,CPT0017450001,CPT0009060003,CPT0012900004,CPT0017410003,CPT0009080003,CPT0012920003,CPT0009000003
0,LAMA5_222_IVPLENGEIVVSLVNGRPGAMnFSYSPLLR_251_2...,15.414611,15.141840,15.609682,15.471691,15.715771,15.582075,15.496776,14.825282,15.022257,...,16.304602,15.577816,15.480282,15.416095,16.211603,16.095162,15.604792,15.304437,15.366103,16.198534
1,ITIH2_113_GAFISnFSMTVDGK_126_6_N4H5F0S1G0,17.194097,17.161645,17.531468,17.326459,18.490422,18.263531,17.662532,18.011022,17.697802,...,17.662301,18.298394,17.844644,17.311183,17.954562,18.296734,17.712529,17.892701,17.804011,17.930018
2,APMAP_196_nMSFVNDLTVTQDGRK_211_1_N2H8F0S0G0,16.141039,16.457631,17.102947,16.635474,16.398802,16.089844,15.935161,16.072948,17.145775,...,15.999110,16.292136,15.647002,16.025746,16.001401,15.964142,15.843208,15.250424,15.183451,16.637151
3,FN1_535_HEEGHMLnCTCFGQGR_550_8_N4H5F0S1G0,14.363901,14.414845,14.800264,14.500603,15.219195,13.421427,14.927323,15.154007,13.987806,...,14.666703,13.947380,14.735971,14.410160,14.935134,14.425399,14.641417,15.268693,14.903590,14.388618
4,CD109_286_InGSANFSFNDEEMK_300_2_N2H8F0S0G0,16.823150,16.708205,18.149726,17.325074,16.910034,16.288521,16.254138,16.395630,17.582609,...,17.729779,17.842208,16.695780,16.955491,16.855874,17.198116,17.100007,17.133722,16.997934,17.908736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10810,LAMA5_3244_LLLGGLPESGTIYnFSGCISNVFVQR_3269_14_...,14.867106,14.887579,14.392180,15.014174,14.883073,14.063906,15.361909,14.435584,14.405460,...,15.041097,14.735240,15.131692,15.048282,14.876406,14.897740,15.353862,15.692505,15.157848,15.196334
10811,CDH6_394_EDAQInTTIGSVTAQDPDAAR_414_6_N5H5F2S0G0,16.117845,16.258365,15.445131,15.494352,15.729901,15.625359,15.808577,16.376311,15.900981,...,14.154636,15.189448,15.689619,16.322294,15.053775,15.759281,15.329724,15.718774,15.322390,14.963758
10812,STAB1_1726_RnVTAAAQGFGYK_1738_2_N2H8F0S0G0,14.476855,14.707436,16.038721,17.058441,15.136480,15.616709,15.878005,14.399267,13.821142,...,16.551848,16.819558,14.530854,15.712289,15.552114,15.647152,16.139644,14.379797,14.927656,15.504176
10813,TFRC_242_DFEDLYTPVnGSIVIVR_258_10_N5H5F1S2G0,13.869988,13.973556,13.995085,15.707804,14.661459,14.855362,14.525548,14.376457,14.922653,...,14.519178,14.642389,13.999922,13.090964,14.180602,14.429359,13.847798,13.688188,13.806605,15.663297
10814,LGALS3BP_64_ALGFEnATQALGR_76_6_N4H5F0S2G0,15.641613,15.549608,15.860276,16.001312,16.076735,16.083150,15.888510,15.628290,15.816233,...,15.546039,16.328455,15.749899,16.282639,16.364148,17.212025,16.490557,16.246464,16.361678,15.792976

In [3]:
# Transpose the dataframe, reset headers and index

df_T = df.T
df_T.columns = df_T.iloc[0]
df_T = df_T[1:]

df_T.reset_index(inplace=True)
df_T

Index,index,LAMA5_222_IVPLENGEIVVSLVNGRPGAMnFSYSPLLR_251_22_N4H5F1S0G0,ITIH2_113_GAFISnFSMTVDGK_126_6_N4H5F0S1G0,APMAP_196_nMSFVNDLTVTQDGRK_211_1_N2H8F0S0G0,FN1_535_HEEGHMLnCTCFGQGR_550_8_N4H5F0S1G0,CD109_286_InGSANFSFNDEEMK_300_2_N2H8F0S0G0,PLXNB2_1031_EAESLQPMTVVGTDYVFHnDTK_1052_19_N5H5F1S0G0,CTSC_51_DVnCSVMGPQEK_62_3_N4H6F0S0G0,FGB_375_YRGTAGNALMDGASQLMGEnR_395_20_N4H5F0S1G0,CLU_97_ELPGVCnETMMALWEECKPCLK_118_7_N4H5F0S2G0,...,BTD_340_NPVGLIGAEnATGETDPSHSK_360_10_N2H5F0S0G0,GNS_356_GPGIKPnQTSK_366_7_N2H5F0S0G0,SERPINA1_64_QLAHQSnSTNIFFSPVSIATAFAMLSLGTK_93_7_N5H5F0S2G0,OLFML3_169_IYVLDGTQnDTAFVFPR_185_9_N4H5F1S0G0,FGG_65_DLQSLEDILHQVEnK_79_14_N5H6F1S1G0,LAMA5_3244_LLLGGLPESGTIYnFSGCISNVFVQR_3269_14_N3H5F0S1G0,CDH6_394_EDAQInTTIGSVTAQDPDAAR_414_6_N5H5F2S0G0,STAB1_1726_RnVTAAAQGFGYK_1738_2_N2H8F0S0G0,TFRC_242_DFEDLYTPVnGSIVIVR_258_10_N5H5F1S2G0,LGALS3BP_64_ALGFEnATQALGR_76_6_N4H5F0S2G0
0,CPT0079430001,15.414611,17.194097,16.141039,14.363901,16.82315,14.832855,13.05617,16.359029,17.979474,...,15.595219,16.896178,14.7729,17.00951,17.00063,14.867106,16.117845,14.476855,13.869988,15.641613
1,CPT0023360001,15.14184,17.161645,16.457631,14.414845,16.708205,14.883942,13.579303,15.945842,17.658734,...,15.522371,17.969214,14.03173,17.223192,15.992055,14.887579,16.258365,14.707436,13.973556,15.549608
2,CPT0023350003,15.609682,17.531468,17.102947,14.800264,18.149726,14.342608,12.847752,16.09394,17.740037,...,14.86381,15.89373,14.174981,16.085713,16.342642,14.39218,15.445131,16.038721,13.995085,15.860276
3,CPT0079410003,15.471691,17.326459,16.635474,14.500603,17.325074,14.425776,12.412877,16.231234,17.220815,...,14.813011,17.535315,14.475654,16.276239,16.769055,15.014174,15.494352,17.058441,15.707804,16.001312
4,CPT0087040003,15.715771,18.490422,16.398802,15.219195,16.910034,14.234945,12.150975,15.950968,16.888709,...,14.752897,15.085696,14.938215,16.071357,16.33028,14.883073,15.729901,15.13648,14.661459,16.076735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,CPT0012900004,16.095162,18.296734,15.964142,14.425399,17.198116,15.357927,11.403616,15.502065,16.530029,...,14.596866,15.774534,15.081243,16.64235,16.043253,14.89774,15.759281,15.647152,14.429359,17.212025
192,CPT0017410003,15.604792,17.712529,15.843208,14.641417,17.100007,14.74174,11.287389,15.585231,17.039707,...,14.751935,15.918554,15.282739,16.357851,16.263307,15.353862,15.329724,16.139644,13.847798,16.490557
193,CPT0009080003,15.304437,17.892701,15.250424,15.268693,17.133722,14.606062,14.117903,16.026908,18.260688,...,15.755052,17.782899,14.774031,17.353575,15.470574,15.692505,15.718774,14.379797,13.688188,16.246464
194,CPT0012920003,15.366103,17.804011,15.183451,14.90359,16.997934,14.506861,12.813975,16.103657,19.029638,...,15.179109,16.671021,14.786574,17.049744,15.761524,15.157848,15.32239,14.927656,13.806605,16.361678
195,CPT0009000003,16.198534,17.930018,16.637151,14.388618,17.908736,14.512838,11.543097,15.525015,16.901983,...,14.536615,15.889964,14.528124,16.104109,15.596775,15.196334,14.963758,15.504176,15.663297,15.792976

In [4]:
# Import biospecimen data, replace blankspace values with NaN, set headers to lowercase

biospecimen = pd.read_csv('../data/PDC_study_biospecimen_09182023_104440.tsv', sep="\t")
biospecimen.replace(r'^\s*$', np.nan, regex=True, inplace=True)

biospecimen.columns = [col.lower() for col in list(biospecimen.columns)]
biospecimen[:3]

,aliquot id,aliquot submitter id,sample id,sample submitter id,case id,case submitter id,project name,sample type,primary site,disease type,...,sample ordinal,shortest dimension,time between clamping and freezing,time between excision and freezing,tissue collection type,tissue type,tumor code,tumor code id,tumor descriptor,program name
0,b64adca6-2053-11e9-b7f8-0a80fada099c,CPT0025170003,b3d4c7a4-204c-11e9-b7f8-0a80fada099c,C3L-00766-01,d610d697-1fb8-11e9-b7f8-0a80fada099c,C3L-00766,CPTAC3 Discovery and Confirmatory,Primary Tumor,Kidney,Clear Cell Renal Cell Carcinoma,...,NaN,NaN,NaN,9.0,NaN,Tumor,NaN,NaN,NaN,Clinical Proteomic Tumor Analysis Consortium
1,1cb3cb3d-2054-11e9-b7f8-0a80fada099c,NCI7-2,fc86d5da-204d-11e9-b7f8-0a80fada099c,NCI7-2,00dc49de-1fba-11e9-b7f8-0a80fada099c,NCI7-2,CPTAC3 Discovery and Confirmatory,Cell Lines,Not Reported,Other,...,NaN,NaN,NaN,NaN,NaN,Not Reported,NaN,NaN,Not Reported,Clinical Proteomic Tumor Analysis Consortium
2,c8117eba-2053-11e9-b7f8-0a80fada099c,CPT0065820001,c85b0efd-204c-11e9-b7f8-0a80fada099c,C3L-00814-02,e63a8d1a-1fb8-11e9-b7f8-0a80fada099c,C3L-00814,CPTAC3 Discovery and Confirmatory,Solid Tissue Normal,Kidney,Clear Cell Renal Cell Carcinoma,...,NaN,NaN,NaN,13.0,NaN,Normal,NaN,NaN,NaN,Clinical Proteomic Tumor Analysis Consortium

In [5]:
# Import clinical data, replace blankspace values with NaN, set headers to lowercase

clinical = pd.read_csv('../data/PDC_study_clinical_09182023_105327.tsv', sep="\t")
clinical.replace(r'^\s*$', np.nan, regex=True, inplace=True)

clinical.columns = [col.lower() for col in list(clinical.columns)]
clinical[:3]

,case id,cases submitter id,related entities,annotation,genomic and imaging data resource,ethnicity,gender,race,morphology,primary diagnosis,...,gleason patterns percent,margin distance,margins involved site,pregnant at diagnosis,satellite nodule present,sites of involvement,tumor depth,who cns grade,who nte grade,diagnosis uuid
0,d610d697-1fb8-11e9-b7f8-0a80fada099c,C3L-00766,NaN,NaN,GDC: https://portal.gdc.cancer.gov/cases/03222...,Not Hispanic or Latino,Female,White,8312/3,"Renal cell carcinoma, NOS",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00dc49de-1fba-11e9-b7f8-0a80fada099c,NCI7-2,NaN,NaN,NaN,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,e63a8d1a-1fb8-11e9-b7f8-0a80fada099c,C3L-00814,NaN,NaN,GDC: https://portal.gdc.cancer.gov/cases/e8bc3...,Not Reported,Male,Not Reported,8312/3,"Renal cell carcinoma, NOS",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Import clinical exposure data, replace blankspace values with NaN, set headers to lowercase

clinical_exposure = pd.read_csv('../data/PDC_study_clinical_exposure_09182023_105327.tsv', sep="\t")
clinical_exposure.replace(r'^\s*$', np.nan, regex=True, inplace=True)

clinical_exposure.columns = [col.lower() for col in list(clinical_exposure.columns)]
clinical_exposure[:3]

,case id,case submitter id,exposure id,exposure submitter id,alcohol days per week,alcohol drinks per day,alcohol history,alcohol intensity,asbestos exposure,cigarettes per day,...,age at onset,alcohol type,exposure duration,exposure duration years,exposure type,marijuana use per week,parent with radiation exposure,secondhand smoke as child,smokeless tobacco quit age,tobacco use per day
0,d610d697-1fb8-11e9-b7f8-0a80fada099c,C3L-00766,1a6eac47-2c37-11ec-b712-0a4e2186f121,C3L-00766-EX,NaN,NaN,Not Reported,Unknown,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,e63a8d1a-1fb8-11e9-b7f8-0a80fada099c,C3L-00814,1af86552-2c37-11ec-b712-0a4e2186f121,C3L-00814-EX,NaN,NaN,Not Reported,Unknown,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,a4300f90-1fb9-11e9-b7f8-0a80fada099c,C3N-01200,1e212588-2c37-11ec-b712-0a4e2186f121,C3N-01200-EX,NaN,NaN,No,Lifelong Non-Drinker,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Import clinical follow up data, replace blankspace values with NaN, set headers to lowercase

clinical_followup = pd.read_csv('../data/PDC_study_clinical_followup_09182023_105327.tsv', sep="\t")
clinical_followup.replace(r'^\s*$', np.nan, regex=True, inplace=True)

clinical_followup.columns = [col.lower() for col in list(clinical_followup.columns)]
clinical_followup[:3]

,case id,case submitter id,follow up id,follow up submitter id,adverse event,adverse event grade,aids risk factors,barretts esophagus goblet cells present,bmi,body surface area,...,risk factor treatment,scan tracer used,undescended testis corrected,undescended testis corrected age,undescended testis corrected laterality,undescended testis corrected method,undescended testis history,undescended testis history laterality,viral hepatitis serologies,weight
0,d610d697-1fb8-11e9-b7f8-0a80fada099c,C3L-00766,84d5f2b3-6c8b-4cc5-a4f7-1e77fe95991a,C3L-00766-FL,NaN,NaN,NaN,NaN,68.59,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167.38
1,e63a8d1a-1fb8-11e9-b7f8-0a80fada099c,C3L-00814,c8445e88-63fa-460e-ac6f-68563169843c,C3L-00814-FL,NaN,NaN,NaN,NaN,30.56,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.62
2,b118086f-1fb8-11e9-b7f8-0a80fada099c,C3L-00026,525353f6-5414-4962-bb9a-beeb8ced2777,C3L-00026-FL,NaN,NaN,NaN,NaN,28.23,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.00

In [8]:
# After merging files, drop duplicate columns with identical values

def drop_dup_columns(df_name):
    dup_cols = [x for x in df_name.columns if "_y" in x]
    num_dropped = 0
    cols_dropped = []

    for col in dup_cols:
        left_col = col.split("_")[0]
        right_col = col
        # Check if columns contains all the same values
        if len(df_name[[left_col,right_col]][df_name[left_col] != df_name[right_col]].dropna(how='all')) == 0:
            df_name.drop(right_col, axis=1, inplace=True)
            num_dropped += 1
            cols_dropped.append(right_col)
        # Check if columns can be merged without changing any values other than NaN
        elif len(df_name[df_name[left_col].fillna(df_name[right_col]) != df_name[right_col].fillna(df_name[left_col])]) == 0:
            df_name[left_col] = df_name[left_col].fillna(df_name[right_col])
            df_name.drop(right_col, axis=1, inplace=True)
            num_dropped += 1
            cols_dropped.append(right_col)
        
    # Print list of columns that do not match    
    if len([x for x in df_name.columns if "_y" in x]) != 0:
        print("Columns do not match", [x for x in df_name.columns if "_y" in x])

    # Print number and list of columns dropped
    print (f"Dropped {num_dropped} duplicate columns")
    for col in cols_dropped:
        print (f"Dropped: {col}")

    return df_name

In [9]:
# Merge abundance and biospecimen dataframes

abundance_biospecimen = pd.merge(df_T,biospecimen, left_on="index", right_on="aliquot submitter id", validate="one_to_one", suffixes=(None, "_y"))
abundance_biospecimen.drop("index", axis=1, inplace=True)
abundance_biospecimen.shape

(191, 10859)

In [10]:
abundance_biospecimen = drop_dup_columns(abundance_biospecimen)
abundance_biospecimen.shape

Dropped 0 duplicate columns

(191, 10859)

In [11]:
# Merge dataframe from previous step with clinical dataframe

abundance_biospecimen_clinical = abundance_biospecimen.merge(clinical, on="case id", validate="many_to_one", suffixes=(None, "_y"))
abundance_biospecimen_clinical.shape

(191, 11010)

In [12]:
abundance_biospecimen_clinical = drop_dup_columns(abundance_biospecimen_clinical)
abundance_biospecimen_clinical.shape

Dropped 4 duplicate columns
Dropped: disease type_y
Dropped: primary site_y
Dropped: program name_y
Dropped: project name_y

(191, 11006)

In [13]:
# Merge dataframe from previous step with clinical exposure dataframe

abundance_biospecimen_clinical_exposure = abundance_biospecimen_clinical.merge(clinical_exposure, on="case id", validate= "many_to_one", suffixes=(None, "_y"))
abundance_biospecimen_clinical_exposure.shape

(183, 11038)

In [14]:
abundance_biospecimen_clinical_exposure = drop_dup_columns(abundance_biospecimen_clinical_exposure)
abundance_biospecimen_clinical_exposure.shape

Dropped 1 duplicate columns
Dropped: case submitter id_y

(183, 11037)

In [15]:
# Merge dataframe from previous step with clinical follow up dataframe

abundance_biospecimen_clinical_exposure_fu = abundance_biospecimen_clinical_exposure.merge(clinical_followup, on="case id", how="left", validate= "many_to_one", suffixes=(None, "_y"))
abundance_biospecimen_clinical_exposure_fu.shape

(183, 11106)

In [16]:
abundance_biospecimen_clinical_exposure_fu = drop_dup_columns(abundance_biospecimen_clinical_exposure_fu)
abundance_biospecimen_clinical_exposure_fu.shape

Columns do not match ['days to recurrence_y', 'progression or recurrence_y']
Dropped 2 duplicate columns
Dropped: case submitter id_y
Dropped: hpv positive type_y

(183, 11104)

In [17]:
# Review duplicate columns that could not be dropped or merged

final_df = abundance_biospecimen_clinical_exposure_fu.copy(deep=True)
final_df[final_df['days to recurrence'] != final_df['days to recurrence_y']][['days to recurrence','days to recurrence_y']].dropna(how='all')

    days to recurrence  days to recurrence_y
2                  NaN                 368.0
3                  NaN                 368.0
16                 NaN                 733.0
17                 NaN                 733.0
29                 NaN                 876.0
30                 NaN                 876.0
92                 NaN                 833.0
93                 NaN                 833.0
98                 NaN                 389.0
99                 NaN                 389.0
101                NaN                 456.0
102                NaN                 456.0
115                NaN                 779.0
116                NaN                 779.0
117                NaN                 594.0
118                NaN                 594.0
123                NaN                 780.0
124                NaN                 780.0
152            1416.00                1416.0

In [18]:
# Drop 'days to recurrence' as the only different rows are NaN

final_df.drop('days to recurrence', axis=1, inplace=True)
final_df.rename(columns={"days to recurrence_y": "days to recurrence"}, inplace=True)
final_df.shape

(183, 11103)

In [19]:
final_df[final_df['progression or recurrence_y'] != final_df['progression or recurrence']][['progression or recurrence','progression or recurrence_y']].dropna(how='any')

    progression or recurrence progression or recurrence_y
115                        No                         Yes
116                        No                         Yes

In [20]:
# Rename 'progression or recurrence_fu' as follow up resulted in a different value

final_df.rename(columns={"progression or recurrence_y": "progression or recurrence_fu"}, inplace=True)
final_df

,LAMA5_222_IVPLENGEIVVSLVNGRPGAMnFSYSPLLR_251_22_N4H5F1S0G0,ITIH2_113_GAFISnFSMTVDGK_126_6_N4H5F0S1G0,APMAP_196_nMSFVNDLTVTQDGRK_211_1_N2H8F0S0G0,FN1_535_HEEGHMLnCTCFGQGR_550_8_N4H5F0S1G0,CD109_286_InGSANFSFNDEEMK_300_2_N2H8F0S0G0,PLXNB2_1031_EAESLQPMTVVGTDYVFHnDTK_1052_19_N5H5F1S0G0,CTSC_51_DVnCSVMGPQEK_62_3_N4H6F0S0G0,FGB_375_YRGTAGNALMDGASQLMGEnR_395_20_N4H5F0S1G0,CLU_97_ELPGVCnETMMALWEECKPCLK_118_7_N4H5F0S2G0,P4HA1_105_DMSDGFISnLTIQR_118_9_N2H6F0S0G0,...,risk factor treatment,scan tracer used,undescended testis corrected,undescended testis corrected age,undescended testis corrected laterality,undescended testis corrected method,undescended testis history,undescended testis history laterality,viral hepatitis serologies,weight
0,15.414611,17.194097,16.141039,14.363901,16.82315,14.832855,13.05617,16.359029,17.979474,16.248994,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0
1,15.471691,17.326459,16.635474,14.500603,17.325074,14.425776,12.412877,16.231234,17.220815,17.775143,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0
2,15.14184,17.161645,16.457631,14.414845,16.708205,14.883942,13.579303,15.945842,17.658734,16.499878,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.0
3,15.609682,17.531468,17.102947,14.800264,18.149726,14.342608,12.847752,16.09394,17.740037,17.990332,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.0
4,15.715771,18.490422,16.398802,15.219195,16.910034,14.234945,12.150975,15.950968,16.888709,17.698439,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,128.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,15.604792,17.712529,15.843208,14.641417,17.100007,14.74174,11.287389,15.585231,17.039707,17.340122,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,16.211603,17.954562,16.001401,14.935134,16.855874,14.341116,11.059163,15.455444,17.018237,17.432247,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,15.304437,17.892701,15.250424,15.268693,17.133722,14.606062,14.117903,16.026908,18.260688,16.242812,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,16.095162,18.296734,15.964142,14.425399,17.198116,15.357927,11.403616,15.502065,16.530029,17.593074,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,15.366103,17.804011,15.183451,14.90359,16.997934,14.506861,12.813975,16.103657,19.029638,16.469135,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN